# Generated by Django 3.2.5 on 2021-07-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boletin', '0003_alter_boletin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votaciones',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
