# Generated by Django 2.2 on 2021-07-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boletin', '0002_auto_20210714_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletin',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='categorias', to='Categoria.Categoria'),
        ),
    ]
